name: Tauri Release

on:
    push:
        branches:
            - upgrades

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                platform: [windows-latest, ubuntu-latest]

        runs-on: ${{ matrix.platform }}

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Install dependencies (Linux)
              if: matrix.platform == 'ubuntu-latest'
              run: |
                  sudo apt update
                  sudo apt install -y \
                    libwebkit2gtk-4.1-dev \
                    libgtk-3-dev \
                    libayatana-appindicator3-dev \
                    librsvg2-dev

            - name: Install frontend deps
              run: npm install

            - name: Get app version
              shell: bash
              id: version
              run: |
                  VERSION=$(node -p "require('./src-tauri/tauri.conf.json').version")
                  echo "VERSION=$VERSION" >> $GITHUB_ENV

            - name: Create tag in release repo
              if: matrix.platform == 'ubuntu-latest'
              run: |
                  git clone https://${{ secrets.RELEASE_REPO_TOKEN }}@github.com/CspmIT/reconecta-front-releases.git
                  cd reconecta-front-releases

                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"

                  TAG="v${VERSION}"

                  if git rev-parse "$TAG" >/dev/null 2>&1; then
                    echo "Tag $TAG already exists"
                  else
                    git tag "$TAG"
                    git push origin "$TAG"
                  fi

            - name: Build Tauri
              uses: tauri-apps/tauri-action@v0.5.16
              env:
                  GITHUB_TOKEN: ${{ secrets.RELEASE_REPO_TOKEN }}
                  VITE_APP_NAME: ${{ secrets.VITE_APP_NAME }}
                  VITE_ENTORNO: ${{ secrets.VITE_ENTORNO }}
                  TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
                  TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
              with:
                  owner: CspmIT
                  repo: reconecta-front-releases
                  tagName: v${{ env.VERSION }}
                  releaseName: 'Reconecta v${{ env.VERSION }}'
                  releaseBody: 'Prueba repo releases'
                  prerelease: false
